name: deploy python 3.7

on:
   push:
       branches:
         -main

env:
    AZURE_WEBAPP_NAME: api2001
    AZURE_WEBAPP_PATH: '.'
    PYTHON_VERSION: '3.8.8'

jobs:
    build-and-deploy:
      runs-on: windows-latest
      steps:

        - uses: action/checkout
        - name: Login via Azure CLI
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CRED }}

        -name: SETUP Python 3.7
         uses: action/setup--python@v1
         with:
          python-version: ${{ env.PYTHON_VERSION }}

        -name: python build + publish
         run: |
          python build --configuration release
          python publish -c Release -o '${{ env.AZURE_WEBAPP_PATH}}/app'

        -name: Deploy to App Service
         uses: azure/webapps-deploy@v2
         with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            package: '${{ env.AZURE_WEBAPP_PATH}}/app'